### ISSUE TITLE
Update this manuscript's thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [sbonaretti/FAIR_metrics#4]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![thumbnail](https://user-images.githubusercontent.com/8326331/64818001-0d281300-d579-11e9-8215-015da333fb5b.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by sbonaretti** [comment]
Hi! Done!
